### PR TITLE
deploy: Make container root file system read only.

### PR DESCRIPTION
**Pull request by avalluri**
It is a best practice to make the containers root file system read-only.

One exception is node driver container - because LVM expect root file
system writable.  Otherwise, all LVM calls fails with error:
"File-based locking initialization failed"

So, driver container root in node daemonset runs with read-write
permission.

Also, avoid using "privileged" when it's not necessary.

### CODE REVIEW

**Comment by pohly** [comment]
@avalluri : needs to be rebased

**Comment by avalluri** [comment]
> @avalluri : needs to be rebased

Done.

**Comment by pohly** [comment]
Something isn't quite right: at the end of https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-656/runs/3/log/?start=0

there's no PMEM available to run a pod:
```
[2020-05-27T23:49:09.874Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0527 23:49:09.499599       1 scheduler.go:178] scheduler "msg"="node filter result" "pod"="inline-volume-tester-sqmm5" "failed nodes"={"pmem-csi-govm-master":"checking for capacity: retrieve capacity: connect to PMEM-CSI on node \"pmem-csi-govm-master\": No node registered with id: pmem-csi-govm-master","pmem-csi-govm-worker1":"only 0B of PMEM available, need 220MiB","pmem-csi-govm-worker2":"only 0B of PMEM available, need 220MiB","pmem-csi-govm-worker3":"only 0B of PMEM available, need 220MiB"} "suitable nodes"=null
```

**Comment by avalluri** [comment]
> Something isn't quite right: at the end of https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-656/runs/3/log/?start=0
> 
> there's no PMEM available to run a pod:
> 
> ```
> [2020-05-27T23:49:09.874Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0527 23:49:09.499599       1 scheduler.go:178] scheduler "msg"="node filter result" "pod"="inline-volume-tester-sqmm5" "failed nodes"={"pmem-csi-govm-master":"checking for capacity: retrieve capacity: connect to PMEM-CSI on node \"pmem-csi-govm-master\": No node registered with id: pmem-csi-govm-master","pmem-csi-govm-worker1":"only 0B of PMEM available, need 220MiB","pmem-csi-govm-worker2":"only 0B of PMEM available, need 220MiB","pmem-csi-govm-worker3":"only 0B of PMEM available, need 220MiB"} "suitable nodes"=null
> ```

I have been working on debugging this, to my surprise I couldn't find any logs about init-containers to check if any issue in initializing LVM volume group:(

**Comment by pohly** [comment]
> I have been working on debugging this, to my surprise I couldn't find any logs about init-containers to check if any issue in initializing LVM volume group:(

You mean in the CI output? That might be a race condition in podlogs: I am not sure if it can get logs for containers that start and stop quickly.

**Comment by avalluri** [comment]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-656/4/tests

`[It] imagefile.ext4 [It] 511Mi` test failed on ClearLinux with `check-imagefile.sh: ERROR: timeout accessing 172.17.0.8 through ssh`

@pohly any quick guesses what could be wrong?

**Comment by pohly** [comment]
Could be a flake. The test needs to boot up a VM, which may have had timing issues.

There were issues with sshd restarting during the VM boot process, but https://github.com/intel/pmem-csi/commit/283a9292ee8735200de09a2e67f2b4fc49e94b02 should have fixed that via retrying.

**Pull request merged**
