### PR TITLE
deploy: test with Kubernetes 1.21 instead of 1.18

### PR DESCRIPTION
**Pull request by pohly**
The deployments for 1.18 get removed in favor of testing with 1.21.
For the two versions which get tested pre-merge, testing of both
"production" and "testing" deployments gets restored the way it
was originally intended (more tests on main worker, less on newly
spawned worker).

Fixes: https://github.com/intel/pmem-csi/issues/978
Fixes: https://github.com/intel/pmem-csi/issues/982
Fixes: https://github.com/intel/pmem-csi/issues/856
Fixes: https://github.com/intel/pmem-csi/issues/730

### CODE REVIEW

**Comment by pohly** [comment]
A newer external-provisioner with https://github.com/kubernetes-csi/external-provisioner/pull/635 is needed for block volumes.

**Comment by pohly** [comment]
The new external-provisioner v2.2.2 should work.

**Comment by pohly** [comment]
Testing was successful, including full testing of the entire branch.

**Review by avalluri — APPROVED** [review]
Looks good to me.

**Pull request merged**
