### PR TITLE
operator merge

### PR DESCRIPTION
**Pull request by pohly**
This merges the operator branch into "devel", at this point without addressing any of the other opens like updating documentation or moving deployment files.

### CODE REVIEW

**Comment by pohly** [comment]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-639/2/consoleFull got stuck during the direct-testing stress test. `worker-8` did not terminate, and the last I could find about it is this attempt to run rmdir:
```
02:13:15.211  [1mSTEP[0m: worker-8-volume-16: done, in 2m31.493899209s
02:13:15.211  May 12 22:08:03.547: INFO: ExecWithOptions {Command:[rmdir /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pmem-sanity-staging.GeMjkK/worker-8] Namespace:default PodName:pmem-csi-node-testing-l78vz ContainerName:socat Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
```

Usually it's quickly followed by `Output: `, but not here.

**Comment by pohly** [comment]
Tests runs are so slow, let me add a commit for issue #624 to this branch.

**Comment by pohly** [comment]
> got stuck during the direct-testing stress test

Can't reproduce that locally.

**Comment by pohly** [comment]
> Tests runs are so slow, let me add a commit for issue #624 to this branch.

In the CI, "make test" time was reduced by 16 minutes.

**Comment by avalluri** [comment]
> Tests runs are so slow, let me add a commit for issue #624 to this branch.
> 
> In the CI, "make test" time was reduced by 16 minutes.

Wav, This was a great improvement.

**Comment by pohly** [comment]
3647cbb75861c0994336faa072a4e70ac4cb88a3 has fixed testing on Kubernetes 1.18 (https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-639/16 and https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-639/17/ for the rebased commits). It's a workaround, but something that we need until Kubernetes does garbage collection as quickly and reliably as previous Kubernetes releases.

6c11ea7c77f86fcb01ce5193c1069d2b685796e2 helped a bit on the operator branch (compare https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/job/operator/ against https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/job/operator2/) but there were still issues. This is mute now, though, because we are moving towards operator development on the "devel" branch.

**Comment by pohly** [comment]
And another clean test run... @avalluri please review and merge.

**Comment by avalluri** [comment]
> And another clean test run... @avalluri please review and merge.

Though I have not done an in-depth review, gone through the changes, and couldn't find any issues.
My feeling is that merging this PR is a high priority, Lets deal in devel even if there are issues discovered after the merge.

Saying that, Looking good to me.

**Pull request merged**
