### PR TITLE
docs links check

### PR DESCRIPTION
**Pull request by pohly**
We want to check links to detect stale external links and anchors that we didn't get right or that changed.

### CODE REVIEW

**Comment by okartau** [comment]
one commit msg has typo:
`skips URLs that only consist of an anchorm`

**Comment by pohly** [comment]
> one commit msg has typo:
> skips URLs that only consist of an anchorm

Fixed. I put that in to keep reviewers on their toes and to check whether they read the commit messages :grin:

**Comment by pohly** [comment]
@okartau is it okay now?

**Comment by okartau** [comment]
yes. I think too it is good idea to get rid of TOC

**Pull request merged**
