### PR TITLE
enable scale testing of PMEM-CSI

### PR DESCRIPTION
**Pull request by pohly**
Normal clusters in the cloud often don't have PMEM. It's still useful to test scalability of the non-local operations on such clusters.

Deploying on a genuine kubeadm-based cluster must allow the controller part to run on the master node.

### CODE REVIEW

**Comment by avalluri** [comment]
The change looks okay to me, but @pohly which part of the change is really enabling the scale testing?

PR requires rebasing.

**Comment by pohly** [comment]
> which part of the change is really enabling the scale testing?

The testing doesn't run in our CI, if that's what you were looking for.

The intended usage is to deploy PMEM-CSI on some cluster manually with the fake device manager instead of LVM or direct.

**Comment by pohly** [comment]
Rebased.

**Comment by avalluri** [comment]
> The intended usage is to deploy PMEM-CSI on some cluster manually with the fake device manager instead of LVM or direct.

Okay, thanks.

**Pull request merged**
