### PR TITLE
Revert "Repository name change: pmem-csi -> csi-pmem"

### PR DESCRIPTION
**Pull request by okartau**
This reverts commit afdf657390af5f1227023e5d9f62849f1258cc24.
Additionally, all other cases of csi-pmem chaned to pmem-csi.

### CODE REVIEW

**Comment by okartau** [comment]
I try to verify this using 3 test methods we have:
1. util/lifecycle-unified: works OK
2. util/sanity-unified:works OK
3. use  make start CLEAR_IMG_VERSION=26460:
I face trouble getting VMs fully set up, but hard to believe current change could affect this.
The only error that I see is failure to connect over ssh to VM:
```
2:+ echo 'systemctl restart systemd-networkd'
2:+ _work/ssh-clear-kvm.2 swupd autoupdate --disable
2:ssh: connect to host 192.168.8.6 port 22: No route to host
2:++ kill_qemu
2:++ touch _work/clear-kvm.2.terminated
```

Here is another, slightly different trace:
```
1:Calling post-update helper scripts.
1:Successfully installed 3 bundles
1:++ kill_qemu
1:++ touch _work/clear-kvm.1.terminated
1:++ '[' 25396 ']'
1:++ kill_process_tree QEMU 25396
1:++ name=QEMU
1:++ pid=25396
1:+++ ps -o pid --ppid 25396 --no-headers
1:++ pids='25410
1:25411'
1:++ '[' '25410
1:25411' ']'
1:++ kill 25410 25411
1:qemu-system-x86_64: terminating on signal 15 from pid 28518 ()
1:+ _work/ssh-clear-kvm.1 swupd clean
1:sh: line 1: 25410 Done                    _work/start-clear-kvm _work/clear-kvm.1.img
1:     25411 Terminated              | tee _work/serial.1.log
1:ssh: connect to host 192.168.8.4 port 22: No route to host
```

seems suddenly test script loses ability to ssh into VM.

**Comment by pohly** [comment]
I'm currently running `make start CLEAR_IMG_VERSION=26460` after `rm -rf _work` on commit 63bb810864dac747f2329424bd7293b33cac51d2 and have no problems with ssh.

Did you already make changes for the test prefix (csipmem -> pmemcsi)?

**Comment by pohly** [comment]
Yes, that change is in, and I was using it already:
```
$ ip route
default via 192.168.1.10 dev eth0 proto static metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.42.1 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.184 metric 100 
192.168.8.0/24 dev pmemcsibr0 scope link linkdown 
```

See the "pmemcsibr0"

**Comment by okartau** [comment]
My previous test problem was related to tester host, not the code change. I rebooted and can repeat full test cycle (CLEAR_IMG_VERSION=26460 and k8s v1.11.3) up to _my-csi-app_ pod and see its Volume with df command, so current PR is not breaking and can be merged

**Comment by okartau** [comment]
force pushed fixing few more old strings/names in README

**Pull request merged**
