### PR TITLE
test: better cluster setup output handling

### PR DESCRIPTION
**Pull request by pohly**
When executing long-running shell scripts on the nodes, the output was
printed in large chunks infrequently. That made it impossible to
really see what's currently happening. Now each line is printed as
soon as it is produced and also gets a time stamp.

swupd prints carriage return characters as part of the download
progress reporting. This used to overwrite the prefix with the node
name. Now those characters are removed before printing. Download
progress ends up producing many lines (one for each update), but
fixing that would require further special handling, so this has to be
good enough for now:

...
09:04:35 pmem-csi-clear-govm-worker2: Downloading packs (398.85 Mb) for:
09:04:35 pmem-csi-clear-govm-worker2: - cloud-native-basic
09:04:35 pmem-csi-clear-govm-worker2: - containers-basic
09:04:35 pmem-csi-clear-govm-worker2: - git
09:04:35 pmem-csi-clear-govm-worker2: - curl
09:04:35 pmem-csi-clear-govm-worker2: - less
09:04:35 pmem-csi-clear-govm-worker2: - iproute2
09:04:35 pmem-csi-clear-govm-worker2: - storage-utils
09:04:35 pmem-csi-clear-govm-worker2: - smartmontools
09:04:35 pmem-csi-clear-govm-worker2: - samba
09:04:35 pmem-csi-clear-govm-worker2: - perl-basic
09:04:35 pmem-csi-clear-govm-worker2: - python3-basic
09:04:35 pmem-csi-clear-govm-worker2: - lib-samba
09:04:35 pmem-csi-clear-govm-worker2: - dosfstools
09:04:35 pmem-csi-clear-govm-worker2: - nfs-utils
09:04:35 pmem-csi-clear-govm-worker2: - openldap
09:04:35 pmem-csi-clear-govm-worker2: - parted
09:04:35 pmem-csi-clear-govm-worker2: - pmdk
09:04:35 pmem-csi-clear-govm-worker2: - xfsprogs
09:04:35 pmem-csi-clear-govm-worker2: 	...0%
09:04:35 pmem-csi-clear-govm-master: 	...8%
09:04:35 pmem-csi-clear-govm-worker1: 	...1%
09:04:35 pmem-csi-clear-govm-master: 	...9%
09:04:35 pmem-csi-clear-govm-worker2: 	...1%
09:04:36 pmem-csi-clear-govm-worker1: 	...2%
09:04:36 pmem-csi-clear-govm-worker2: 	...2%
09:04:36 pmem-csi-clear-govm-worker3: Downloading packs (398.85 Mb) for:
09:04:36 pmem-csi-clear-govm-worker3: - cloud-native-basic
09:04:36 pmem-csi-clear-govm-worker3: - containers-basic
09:04:36 pmem-csi-clear-govm-worker3: - git
09:04:36 pmem-csi-clear-govm-worker3: - curl
09:04:36 pmem-csi-clear-govm-worker3: - less
09:04:36 pmem-csi-clear-govm-worker3: - iproute2
09:04:36 pmem-csi-clear-govm-worker3: - storage-utils
09:04:36 pmem-csi-clear-govm-worker3: - smartmontools
09:04:36 pmem-csi-clear-govm-worker3: - samba
09:04:36 pmem-csi-clear-govm-worker3: - perl-basic
09:04:36 pmem-csi-clear-govm-worker3: - python3-basic
09:04:36 pmem-csi-clear-govm-worker3: - lib-samba
09:04:36 pmem-csi-clear-govm-worker3: - dosfstools
09:04:36 pmem-csi-clear-govm-worker3: - nfs-utils
09:04:36 pmem-csi-clear-govm-worker3: - openldap
09:04:36 pmem-csi-clear-govm-worker3: - parted
09:04:36 pmem-csi-clear-govm-worker3: - pmdk
09:04:36 pmem-csi-clear-govm-worker3: - xfsprogs
09:04:36 pmem-csi-clear-govm-worker3: 	...0%
09:04:36 pmem-csi-clear-govm-worker2: 	...3%
09:04:36 pmem-csi-clear-govm-master: 	...10%
09:04:36 pmem-csi-clear-govm-worker1: 	...3%
09:04:36 pmem-csi-clear-govm-worker2: 	...4%
09:04:36 pmem-csi-clear-govm-worker3: 	...1%
...

### CODE REVIEW

**Comment by okartau** [comment]
The output does not look entirely reasonable.
I saw about 25 minutes of full-speed-scrolling output as this (below), from all nodes and master.
Those percent numbers started at low values but went up, and those values dont seem reasonable at all.
I did not count lines but there were millions, estimating by speed and time.
Just emitting those lines likely adds lot of overhead to duration.
For me, this is not just improvement over what we had.
Any way avoiding those silly lines which don't carry any useful information?

11:31:48 pmem-csi-clear-govm-master:    ...613290%
11:31:48 pmem-csi-clear-govm-master:    ...613303%
11:31:48 pmem-csi-clear-govm-master:    ...613317%
11:31:48 pmem-csi-clear-govm-master:    ...613331%

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> The output does not look entirely reasonable.
> I saw about 25 minutes of full-speed-scrolling output as this (below), from all nodes and master.
> Those percent numbers started at low values but went up, and those values dont seem reasonable at all.
> I did not count lines but there were millions, estimating by speed and time.
> Just emitting those lines likely adds lot of overhead to duration.
> For me, this is not just improvement over what we had.

The output without my changes also has all of those lines (from
current devel branch), it just looks weirder:

```
pmem-csi-clear-govm-worker3:  - xfsprogs
pmem-csi...0%r-govm-worker3: 
pmem-csi...1%r-govm-worker3: 
pmem-csi...2%r-govm-worker3: 
pmem-csi...3%r-govm-worker3: 
pmem-csi...4%r-govm-worker3: 
pmem-csi...5%r-govm-worker3: 
pmem-csi...6%r-govm-worker3: 
pmem-csi...7%r-govm-worker3: 
pmem-csi...8%r-govm-worker3: 
pmem-csi...9%r-govm-worker3: 
pmem-csi...10%-govm-worker3: 
pmem-csi...11%-govm-worker3: 
pmem-csi...12%-govm-worker3: 
pmem-csi...13%-govm-worker3: 
pmem-csi...14%-govm-worker3: 
pmem-csi...15%-govm-worker3: 
pmem-csi...16%-govm-worker3: 
pmem-csi...17%-govm-worker3: 
pmem-csi...18%-govm-worker3: 
pmem-csi...19%-govm-worker3: 
pmem-csi...20%-govm-worker3: 
pmem-csi...21%-govm-worker3: 
pmem-csi...22%-govm-worker3: 
pmem-csi...23%-govm-worker3: 
pmem-csi...24%-govm-worker3: 
pmem-csi...25%-govm-worker3: 
pmem-csi...26%-govm-worker3: 
pmem-csi...27%-govm-worker3: 
pmem-csi...28%-govm-worker3: 
pmem-csi...29%-govm-worker3: 
pmem-csi...30%-govm-worker3: 
pmem-csi...31%-govm-worker3: 
pmem-csi...32%-govm-worker3: 
pmem-csi...33%-govm-worker3: 
pmem-csi...34%-govm-worker3: 
pmem-csi...35%-govm-worker3: 
pmem-csi...36%-govm-worker3: 
pmem-csi...37%-govm-worker3: 
pmem-csi...38%-govm-worker3: 
pmem-csi...39%-govm-worker3: 
pmem-csi...40%-govm-worker3: 
pmem-csi...41%-govm-worker3: 
pmem-csi...42%-govm-worker3: 
pmem-csi...43%-govm-worker3: 
pmem-csi...44%-govm-worker3: 
pmem-csi...45%-govm-worker3: 
pmem-csi...46%-govm-worker3: 
pmem-csi...47%-govm-worker3: 
pmem-csi...48%-govm-worker3: 
pmem-csi...49%-govm-worker3: 
pmem-csi...50%-govm-worker3: 
pmem-csi...51%-govm-worker3: 
pmem-csi...52%-govm-worker3: 
pmem-csi...53%-govm-worker3: 
pmem-csi...54%-govm-worker3: 
pmem-csi...55%-govm-worker3: 
pmem-csi...56%-govm-worker3: 
pmem-csi...57%-govm-worker3: 
pmem-csi...58%-govm-worker3: 
pmem-csi...59%-govm-worker3: 
pmem-csi...60%-govm-worker3: 
pmem-csi...61%-govm-worker3: 
pmem-csi...62%-govm-worker3: 
pmem-csi...6pmem-csi-clear-govm-master: + set -o errexit
....
pmem-csi-clear-govm-master:  - parted
pmem-csi-clear-govm-master:  - pmdk
pmem-csi-clear-govm-master:  - xfsprogs
pmem-csi...0%r-govm-master: 
pmem-csi...1%r-govm-master: 
pmem-csi...2%r-govm-master: 
pmem-csi...3%r-govm-master: 
pmem-csi...4%r-govm-master: 
pmem-csi...5%r-govm-master: 
pmem-csi...6%r-govm-master: 
pmem-csi...7%r-govm-master: 
pmem-csi...8%r-govm-master: 
pmem-csi...9%r-govm-master: 
pmem-csi...10%-govm-master: 
pmem-csi...11%-govm-master: 
pmem-csi...12%-govm-master: 
pmem-csi...13%-govm-master: 
pmem-csi...14%-govm-master: 
pmem-csi...15%-govm-master: 
pmem-csi...16%-govm-master: 
pmem-csi...17%-govm-master: 
pmem-csi...18%-govm-master: 
pmem-csi...19%-govm-master: 
pmem-csi...20%-govm-master: 
pmem-csi...21%-govm-master: 
pmem-csi...22%-govm-master: 
pmem-csi...23%-govm-master: 
pmem-csi...24%-govm-master: 
pmem-csi...25%-govm-master: 
pmem-csi...26%-govm-master: 
pmem-csi...27%-govm-master: 
pmem-csi...28%-govm-master: 
pmem-csi...29%-govm-master: 
pmem-csi...30%-govm-master: 
pmem-csi...31%-govm-master: 
pmem-csi...32%-govm-master: 
pmem-csi...33%-govm-master: 
pmem-csi...34%-govm-master: 
pmem-csi...35%-govm-master: 
pmem-csi...36%-govm-master: 
pmem-csi...37%-govm-master: 
pmem-csi...38%-govm-master: 
pmem-csi...39%-govm-master: 
pmem-csi...40%-govm-master: 
pmem-csi...41%-govm-master: 
pmem-csi...42%-govm-master: 
pmem-csi...43%-govm-master: 
pmem-csi...44%-govm-master: 
pmem-csi...45%-govm-master: 
pmem-csi...46%-govm-master: 
pmem-csi...47%-govm-master: 
pmem-csi...48%-govm-master: 
pmem-csi...49%-govm-master: 
pmem-csi...50%-govm-master: 
pmem-csi...51%-govm-master: 
pmem-csi...52%-govm-master: 
pmem-csi...53%-govm-master: 
pmem-csi...54%-govm-master: 
pmem-csi...55%-govm-master: 
pmem-csi...56%-govm-master: 
pmem-csi...57%-govm-master: 
pmem-csi...58%-govm-master: 
pmem-csi...59%-govm-master: 
pmem-csi...60%-govm-master: 
pmem-csi...61%-govm-master: 
pmem-csi...62%-govm-master: 
pmem-csi...63%-govm-master: 
pmem-csi...64%-govm-master: 
pmem-csi...65%-govm-master: 
pmem-csi-clear-govm-pmem-csi-clear-govm-worker2: + set -o errexit
...
```

> Any way avoiding those silly lines which don't carry any useful information?
>
> 11:31:48 pmem-csi-clear-govm-master:    ...613290%
> 11:31:48 pmem-csi-clear-govm-master:    ...613303%
> 11:31:48 pmem-csi-clear-govm-master:    ...613317%
> 11:31:48 pmem-csi-clear-govm-master:    ...613331%

*That* is the actual problem, not my changes. Why does swupd print percentages higher
than 100?!

Just to be sure, can you try in your environment without this PR?

**Comment by okartau** [comment]
I tried same `make start` setting git commit earlier-by-one. The output seems reasonable, total 2200 lines, with few percents-series 0..100% what makes sense.
(My "millions of lines" guess earlier was bit overestimate, actually there was about 300k lines)

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> I tried same `make start` setting git commit earlier-by-one. The output seems reasonable, total 2200 lines, with few percents-series 0..100% what makes sense.
> (My "millions of lines" guess earlier was bit overestimate, actually
> there was about 300k lines)

Can you archive your current _work/clear-govm/*.log files?  Then try
again with this PR and send me the console output (redirected into a
file) and the individual _work/clear-govm/*.log files?

I have no idea where those additional lines come from and I can't
reproduce it here.

**Comment by okartau** [comment]
I tried now, and I see good-looking output, even shorter than before with 1600 lines. Seems that whatever problem I had with long output, it's not triggered directly by this PR change.
Rebasing would fix disharmony between deployment files and head of devel, where namespacesize option was removed, causing failure to start pods using latest images and this PR deploy files.

**Comment by okartau** [comment]
> whatever problem I had with long output

problem was likely clear swupd related. But as the base has moving parts with base release changing often and causing update set/process also becoming dynamic, we can't expect seeing reproducible cases without freezing moving parts (which we will not need/plan anyway)

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> I tried now, and I see good-looking output, even shorter than before
> with 1600 lines. Seems that whatever problem I had with long output,
> it's not triggered directly by this PR change.

Yep. It would have been very surprising if it had been.

> Rebasing would fix disharmony between deployment files and head of
> devel, where namespacesize option was removed, causing failure to
> start pods using latest images and this PR deploy files.

This PR does not change the deployment. Why should rebasing fix
anything?

I have rebased anyway, just to be sure.

**Comment by okartau** [comment]
> Why should rebasing fix anything?

it fixes deployment for people who use external registry, like me. I have images in registry built from head of devel, which are not deployable with older deploy file set, as there is "-namespacesize" option in deploy files which is not supported by current images. I should go back in time with images as well to test full set here. but as our images build is so slow these days, I select to skip it and accept the "known partial failure", but that's not so clean.

**Pull request merged**
