### PR TITLE
Use ndctl version 67

### PR DESCRIPTION
**Pull request by okartau**
New version has just been released, lets see how this goes in our CI

### CODE REVIEW

**Comment by pohly** [comment]
Looks fine to me, let's merge after the CI is done with testing it.

**Comment by pohly** [comment]
@okartau did you force-push to trigger a CI build? That can also be done by logging into the Jenkins UI. Then reviewers don't need to check the diff again.

**Comment by okartau** [comment]
> @okartau did you force-push to trigger a CI build? That can also be done by logging into the Jenkins UI. Then reviewers don't need to check the diff again.

it was rebase to latest devel and force push. I know rebase is not mandatory most of time but I sometimes I do it anyway to keep  things up to date. I need to comment then to avoid extra checking need.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> it was rebase to latest devel and force push. I know rebase is not
> mandatory most of time but I sometimes I do it anyway to keep  things
> up to date.

I don't think that this is necessary unless there really is a code
conflict. It just causes extra churn.

**Pull request merged**
