### PR TITLE
WIP: deployment changes to support kubernetes v1.12

### PR DESCRIPTION
**Pull request by avalluri**
[This is not tested yet, Please **don't merge**]
Signed-off-by: Amarnath Valluri <amarnath.valluri@intel.com>

### CODE REVIEW

**Comment by okartau** [comment]
I applied the changes from this PR on top of latest devel, and I get _my-csi-app_ running with mounted volume in k8s version 1.12.3, that's good news. Node pods remain running without crash.
However, there is still something wrong with master pod which gets restarted in CrashLoopBackOff state,
it's log is showing:
```
I1209 22:39:26.151322       1 main.go:153] Calling CSI driver to discover driver name.
I1209 22:39:26.151328       1 connection.go:136] GRPC call: /csi.v0.Identity/GetPluginInfo
I1209 22:39:26.151331       1 connection.go:137] GRPC request: 
I1209 22:39:26.152170       1 connection.go:139] GRPC response: name:"pmem-csi" vendor_version:"0.0.1" 
I1209 22:39:26.152217       1 connection.go:140] GRPC error: <nil>
I1209 22:39:26.152223       1 main.go:161] CSI driver name: "pmem-csi"
I1209 22:39:26.152228       1 main.go:165] Loading kubeconfig.
E1209 22:39:26.152406       1 main.go:179] Unknown mode: kubelet-register
```

**Comment by avalluri** [comment]
@olev, i think the driver-registrar's "kubelet-register" option has renamed to  "kubernetes-register". Can you try with this chang in our yaml.

**Comment by okartau** [comment]
I force-pushed new state here, with 2 commits renaming deploy/k8s and adding deploy/kubernetes-1.12.
The only changed file there is pmem-csi.yaml, others being symlinks.
The open case right now is pmem-unified-csi.yaml which has not been yet verified/tried on 1.12.
Note that e2e testing code refers deploy/ files directly so it has to hard-code kubernetes or kubernetes-1.12

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Note that e2e testing code refers deploy/ files directly so it has to
> hard-code kubernetes or kubernetes-1.12

It would be possible to add a command line flag to the test to set the
directory, or let it query the running Kubernetes version and switch
accordingly.

**Comment by okartau** [comment]
I propose we create another PR for e2e changes which needs work anyway as per #101, and merge this PR to get 1.12 support functional. Anyone wants to verify this to get additional confirmation that it works on another setup apart from mine?

**Comment by avalluri** [comment]
I will test this and let you know Olev

**Comment by avalluri** [comment]
I tested this PR on my local cluster, found no issues. +1

**Pull request merged**
