### PR TITLE
Fix version skew

### PR DESCRIPTION
**Pull request by pohly**
Re-enabling the version skew tests and running tests manually showed that there were some issues.

### CODE REVIEW

**Comment by avalluri** [comment]
Looks good to me. Let's merge once it passes the CI.

**Comment by pohly** [comment]
Version skew testing is failing on Kubernetes 1.21 because 0.9 didn't support it. There's also a problem with downgrading via the operator on 1.21: the new operator sets storageCapacity:true and the old one tries to patch that to false, but that then fails because CSIDriver is immutable. I'll work around that in the operator for the more important upgrade scenario and disable testing of downgrades.

**Review by pohly — COMMENTED** [review]
"operator versionskew downgrade [Slow]" also fails when testing with 1.19. The test failure isn't very informative and I don't know what to look for in the logs:
```
• Failure [329.783 seconds]
operator
/nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1386
  versionskew
  /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1371
    downgrade [Slow] [It]
    /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/versionskew/operator.go:221

    Jul 15 16:45:23.300: Timed out after 300.001s.
    before version downgrade: reconcile driver deployments:
    Expected
        <bool>: false
    to be true
```

I'll probably just disable the downgrade testing entirely.

**Comment by avalluri** [comment]
> "operator versionskew downgrade [Slow]" also fails when testing with 1.19. The test failure isn't very informative and I don't know what to look for in the logs:
> 
> ```
> • Failure [329.783 seconds]
> operator
> /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1386
>   versionskew
>   /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/deploy/deploy.go:1371
>     downgrade [Slow] [It]
>     /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/versionskew/operator.go:221
> 
>     Jul 15 16:45:23.300: Timed out after 300.001s.
>     before version downgrade: reconcile driver deployments:
>     Expected
>         <bool>: false
>     to be true
> ```
> 
> I'll probably just disable the downgrade testing entirely.

For some reason, the driver deployment before downgrade has not reached to 'Ready' state.

**Pull request merged**
