### PR TITLE
test: used fixed sort order

### PR DESCRIPTION
**Pull request by okartau**
The ordering of text files is locale-specific. When comparing against
the reference files we have to ensure that the same ordering is used
regardless of the environment and/or the actual "sort" implementation.

LC_ALL=C ensures that for GNU sort and glibc. LANG=C is added just as
an extra precaution for other implementations.

### CODE REVIEW

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> The ordering of text files is locale-specific. When comparing against
> the reference files we have to ensure that the same ordering is used
> regardless of the environment and/or the actual "sort" implementation.
>
> LC_ALL=C ensures that for GNU sort and glibc. LANG=C is added just as
> an extra precaution for other implementations.

Please let's merge my other PRs first. It'll be easier to redo this
change here on top of those (just sort the vendor-bom.csv) than to
manually sort out merge conflicts.

**Comment by okartau** [comment]
I created PR just to get it closer to merge.
Perhaps commit msg should be cleaned as well here

**Comment by avalluri** [comment]
@pohly your other PR is merged, can you please rebase this

**Comment by avalluri** [comment]
Thanks @pohly , looks good. I will merge this change.

**Pull request merged**
