### PR TITLE
Go vendor test

### PR DESCRIPTION
**Pull request by pohly**
Ensure that go.mod, go.sum and vendor are up-to-date.

### CODE REVIEW

**Comment by pohly** [comment]
This depends on #461 

The test is currently expected to fail, because in the current version of that PR the go.sum file was not up-to-date (`go mod tidy` not called).

**Comment by pohly** [comment]
Worked as expected (https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-466/1/console):

```
13:15:43  go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
13:15:43  go: extracting github.com/konsorten/go-windows-terminal-sequences v1.0.2
13:15:43  go: extracting github.com/opencontainers/go-digest v1.0.0-rc1
13:15:43  ERROR: go module files *not* up-to-date, they did get modified by 'GO111MODULE=on go mod tidy':
13:15:43  diff --git a/go.sum b/go.sum
13:15:43  index 15772219..02b1f941 100644
13:15:43  --- a/go.sum
13:15:43  +++ b/go.sum
13:15:43  @@ -696,8 +696,6 @@ k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51 h1:RBkTKVMF+xsNsSOVc0+HdC0B5gD
13:15:43   k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51/go.mod h1:gL826ZTIfD4vXTGlmzgTbliCAT9NGiqpCqK2aNYv5MQ=
13:15:43   k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2 h1:YXArqZfchiY+62+AyWPWE59wICh7xnAEowHGWggxBXs=
13:15:43   k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2/go.mod h1:SBvrtLbuePbJygVXGGCMtWKH07+qrN2dE1iMnteSG8E=
13:15:43  -k8s.io/kubernetes v1.16.2 h1:k0f/OVp6Yfv+UMTm6VYKhqjRgcvHh4QhN9coanjrito=
13:15:43  -k8s.io/kubernetes v1.16.2/go.mod h1:SmhGgKfQ30imqjFVj8AI+iW+zSyFsswNErKYeTfgoH0=
13:15:43   k8s.io/kubernetes v1.17.0-alpha.0.0.20191109043140-c3f2a6524ed8 h1:+6/wrEXyQxJU5/Y6X4fqRtRpqP6rJASAqI7bBigJpF0=
13:15:43   k8s.io/kubernetes v1.17.0-alpha.0.0.20191109043140-c3f2a6524ed8/go.mod h1:hJd0X6w7E/MiE7PcDp11XHhdgQBYc33vP+WtTJqG/AU=
13:15:43   k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b h1:cgLCVtQnxjALxIUjjEkiMaKlQZW5sGj6P3+3K5Y/d+8=
13:15:43  @@ -707,8 +705,6 @@ k8s.io/repo-infra v0.0.0-20181204233714-00fe14e3d1a3/go.mod h1:+G1xBfZDfVFsm1Tj/
13:15:43   k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9/go.mod h1:sXltHZrQa4jdKL14nOFRRUhhzpmbnRF0qGuAhRQbaxc=
13:15:43   k8s.io/utils v0.0.0-20190801114015-581e00157fb1 h1:+ySTxfHnfzZb9ys375PXNlLhkJPLKgHajBU0N62BDvE=
13:15:43   k8s.io/utils v0.0.0-20190801114015-581e00157fb1/go.mod h1:sZAwmy6armz5eXlNoLmJcl4F1QuKu7sr+mFQ0byX7Ew=
13:15:43  -k8s.io/utils v0.0.0-20191010214722-8d271d903fe4 h1:Gi+/O1saihwDqnlmC8Vhv1M5Sp4+rbOmK9TbsLn8ZEA=
13:15:43  -k8s.io/utils v0.0.0-20191010214722-8d271d903fe4/go.mod h1:sZAwmy6armz5eXlNoLmJcl4F1QuKu7sr+mFQ0byX7Ew=
13:15:43   modernc.org/cc v1.0.0/go.mod h1:1Sk4//wdnYJiUIxnW8ddKpaOJCF37yAdqYnkxUpaYxw=
13:15:43   modernc.org/golex v1.0.0/go.mod h1:b/QX9oBD/LhixY6NDh+IdGv17hgB+51fET1i2kPSmvk=
13:15:43   modernc.org/mathutil v1.0.0/go.mod h1:wU0vUrJsVWBZ4P6e7xtFJEhFSNsfRLJ8H458uRjg03k=
13:15:43  make: *** [test/test.make:43: test_vendor] Error 1
```

**Comment by avalluri** [comment]
I fixed g

> This depends on #461
> 
> The test is currently expected to fail, because in the current version of that PR the go.sum file was not up-to-date (`go mod tidy` not called).

I fixed this in #461. Can you please rebase.

**Comment by avalluri** [comment]
@pohly As part of this change, Can you make `test_vendor_bom` target work again with go modules. This was left as TODO in #461.

**Comment by pohly** [comment]
> Can you make test_vendor_bom target work again with go modules. This was left as TODO in #461.

I didn't know that. There's no such TODO in https://github.com/intel/pmem-csi/blob/56dce6af8fcee904c95ebd0c44a30109175f5b4e/test/test.make#L23-L36 and as it wasn't failing, I assumed that you had changed it.

I can try to fix it. But unless I come up with something, we can't merge #461. Having our process in working shape is more important than moving to Go 1.13.

**Comment by avalluri** [comment]
> > Can you make test_vendor_bom target work again with go modules. This was left as TODO in #461.
> 
> I didn't know that. There's no such TODO in


TODO was in Commit message:

```
TODO: We can drop Gopkg.lock file, but 'test_vendor_bom' make target uses this
file to retrieve the package list to validate vendor tree. One should replace
this check with go module equivalent.
```

> I can try to fix it. But unless I come up with something, we can't merge #461. Having our process in working shape is more important than moving to Go 1.13.

I agree.

**Comment by pohly** [comment]
> TODO was in Commit message:

I read that once, but didn't go back to check whether it's still there. It also doesn't show up in the GitHub diffs and would not have been found by "git grep TODO" if we had merged the PR. When the PR was no longer marked as WIP, I assumed that it is complete.

Anyway, please cherry-pick 9682ae70 into your branch.

**Comment by pohly** [comment]
@avalluri : rebased, please approve.

**Pull request merged**
