### PR TITLE
WIP: unit testing minor cleanup and improvement

### PR DESCRIPTION
**Pull request by okartau**
Showing tests coverage is overall useful, let's have it.
Also, use TEST_CMD in two invocations instead of just one.

### CODE REVIEW

**Comment by okartau** [comment]
I think showing coverage is overall useful, it indicates how well (or sometimes, how badly) the testing code covers all code. For example, right now we get with added -cover option, unit tests:
```
ok      github.com/intel/pmem-csi/pkg/pmem-csi-driver   coverage: 5.8% of statements
```

Same option also applicable in e2e test (this PR adds it in both), where we now get:
```
ok       github.com/intel/pmem-csi/test/e2e      1590.494s       coverage: 62.5% of statements
```

With coverage analysis, it's also easy to get coverage shown line-by-line (html-formatted output) so it's easy to see the areas which remain uncovered. But that part is not in this PR.

**Comment by pohly** [comment]
> Same option also applicable in e2e test (this PR adds it in both), where we now get:

This most likely is the test coverage of the code in the *test suite* itself (i.e. all code outside of `_test.go` which gets linked into `e2e.test`), which isn't useful. What we would need is some way to collect coverage information of the PMEM-CSI binaries running in the cluster and then combine that with different unit test runs. I don't know how to do that.

**Comment by okartau** [comment]
> This most likely is the test coverage of the code in the _test suite_ itself

good point, means we should not add -cover option in e2e case, I will take it away

**Comment by okartau** [comment]
As I found some dead-looking code and leftover OIM reference in comment, I added 2nd commit and rename this PR to be more generic unit-test improvement

**Comment by okartau** [comment]
I cherry-picked two commits from here into #246, so we can close this now

**Pull request closed without merging**
