### PR TITLE
Devicemanager enhancements

### PR DESCRIPTION
**Pull request by avalluri**
Added two new fields to PmemDeviceInfo structure:
 - Mode : holds the device namespace mode 
 - NumaNode: hods the numa node to which the device attached to

In LVM mode we use the volume group tags for storing these details.

### CODE REVIEW

**Comment by pohly** [comment]
Can you explain why this is useful?

**Comment by avalluri** [comment]
> Can you explain why this is useful?

NSMode: 
As I made a note here: https://github.com/intel/pmem-csi/pull/383/files#diff-4a0caa0c2e37db715640b7cbf97d7a1fR263-R267 , the PMEM device should have a way to knowin which mode it was created, currently this information is with VolumeContext, but I feel the right place is PmemDeviceInfo structure.

NumaNode:
Its just an enabler change to make the driver numa aware, though the solution is still under investigation. Numa APIs in ndctl layer are useful to know a pmem region's numa  node, if we wants to support PMEM device creation in given numa node region.

**Comment by pohly** [comment]
@avalluri: do we still need this PR?

**Comment by avalluri** [comment]
> @avalluri: do we still need this PR?

Yes, I believe. It would be useful at least logging NUMA node related information of a device.

**Comment by pohly** [comment]
@avalluri : is this PR still relevant?

**Comment by avalluri** [comment]
> @avalluri : is this PR still relevant?

Yes if we need to track/log the numa node details of a volume. If not we can ignore and close the PR.

**Comment by pohly** [comment]
> Yes if we need to track/log the numa node details of a volume

I don't think we have such a requirement. Are you aware of one? You were working with Sasha on NUMA.

**Comment by avalluri** [comment]
> > Yes if we need to track/log the numa node details of a volume
> 
> I don't think we have such a requirement. Are you aware of one? You were working with Sasha on NUMA.

There is no such requirement enforced by CRI-RM. But in general, I feel like there is no easy way to know to which NUMA node a particular PMEM-CSI volume is attached to while debugging the performance of an application that using this volume.

**Comment by pohly** [comment]
> I feel like there is no easy way to know to which NUMA node a particular PMEM-CSI volume is attached to while debugging the performance of an application that using this volume.

So you want to expose that to the user? That seems worthwhile, but then we also need to define how users actually get that information. Log file parsing IMHO shouldn't be the answer.

**Comment by pohly** [comment]
> Log file parsing IMHO shouldn't be the answer.

Perhaps some metric? We should explore further what we can do with those.

**Comment by avalluri** [comment]
> > Log file parsing IMHO shouldn't be the answer.
> 
> Perhaps some metric? We should explore further what we can do with those.

Yes, I agree.

**Comment by pohly** [comment]
@avalluri can we close this PR until there is a need for it?

**Comment by avalluri** [comment]
> @avalluri can we close this PR until there is a need for it?

Okay.

**Pull request closed without merging**
