### PR TITLE
dependency update

### PR DESCRIPTION
**Pull request by pohly**
This is the result of `go get -u ./...` with some manual tweaks:
- gopkg.in/square/go-jose.v2@v2.2.2 and google.golang.org/grpc@v1.27.0
  because that is what Kubernetes uses and newer versions
  changed the API such that Kubernetes code doesn't compile
- github.com/operator-framework/operator-sdk/version was made
  an internal package, so we can't use it anymore
- github.com/operator-framework/operator-sdk/pkg/restmapper was
  removed - we don't seem to need it anymore

Fixes: https://github.com/intel/pmem-csi/issues/756

### CODE REVIEW

**Comment by pohly** [comment]
For some reason, this PR causes the deployment to not match the test:

https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-764/runs/1/nodes/90/steps/142/log/?start=0

```
[2020-10-01T17:48:57.487Z] [1mSTEP[0m: preparing for test "operator API deployment with defaults" in namespace default
[2020-10-01T17:48:58.259Z] Oct  1 17:48:58.012: INFO: No external IP address on nodes, falling back to internal IPs
[2020-10-01T17:48:58.259Z] Oct  1 17:48:58.018: INFO: reusing existing lvm-testing PMEM-CSI components
[2020-10-01T17:48:58.259Z] Oct  1 17:48:58.018: INFO: Waiting for PMEM-CSI driver.
```

It shouldn't be "reusing existing lvm-testing" here.

**Comment by avalluri** [comment]
> For some reason, this PR causes the deployment to not match the test:
> 
> https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-764/runs/1/nodes/90/steps/142/log/?start=0
> 
> ```
> [2020-10-01T17:48:57.487Z] �[1mSTEP�[0m: preparing for test "operator API deployment with defaults" in namespace default
> [2020-10-01T17:48:58.259Z] Oct  1 17:48:58.012: INFO: No external IP address on nodes, falling back to internal IPs
> [2020-10-01T17:48:58.259Z] Oct  1 17:48:58.018: INFO: reusing existing lvm-testing PMEM-CSI components
> [2020-10-01T17:48:58.259Z] Oct  1 17:48:58.018: INFO: Waiting for PMEM-CSI driver.
> ```
> 
> It shouldn't be "reusing existing lvm-testing" here.

It's bit strange, it shouldn't reuse "lvm-testing" for running operator API tests.

**Comment by pohly** [comment]
> It's bit strange, it shouldn't reuse "lvm-testing" for running operator API tests.

`ginkgo.Describe` changed it's behavior from "invoke callback function immediately" to "store function and call later". I suspected that already yesterday, but then didn't see that in a debugger - must have been looking at the wrong code. When I ran it again today, I saw the different stack trace that confirmed this theory. Gets addressed in in https://github.com/intel/pmem-csi/pull/764/commits/bae6ec93999b23f1664de51f78a3cbc4dc7fb5f9

**Comment by pohly** [comment]
We need https://github.com/kubernetes-csi/csi-lib-utils/pull/67 and must suppress `process_start_time`, otherwise metric gathering fails with:
```
gathered metric family process_start_time_seconds has help "[ALPHA] Start time of the process since unix epoch in seconds." but should have "Start time of the process since unix epoch in seconds."
```

**Comment by pohly** [comment]
@avalluri : this is ready for review.

**Review by avalluri — APPROVED** [review]
Looks good.

**Pull request merged**
