### PR TITLE
operator: drop using forked repo

### PR DESCRIPTION
**Pull request by avalluri**
FXIES #839

### CODE REVIEW

**Comment by avalluri** [comment]
One more concurrent map access random failure:
```
[2021-01-30T10:30:44.797Z] ?   	github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller	[no test files]
[2021-01-30T10:31:19.390Z] fatal error: concurrent map read and map write
[2021-01-30T10:31:19.390Z] 
[2021-01-30T10:31:19.390Z] goroutine 840 [running]:
[2021-01-30T10:31:19.390Z] runtime.throw(0x17ba129, 0x21)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/panic.go:1116 +0x72 fp=0xc000c5a5f8 sp=0xc000c5a5c8 pc=0x439552
[2021-01-30T10:31:19.390Z] runtime.mapaccess2(0x15fe060, 0xc0001bcbd0, 0xc00057f5a0, 0xc00057f5a0, 0xc001068a02)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/map.go:469 +0x25b fp=0xc000c5a638 sp=0xc000c5a5f8 pc=0x41147b
[2021-01-30T10:31:19.390Z] reflect.mapaccess(0x15fe060, 0xc0001bcbd0, 0xc00057f5a0, 0x17adb9e)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/map.go:1309 +0x3f fp=0xc000c5a670 sp=0xc000c5a638 pc=0x46ab3f
[2021-01-30T10:31:19.390Z] reflect.Value.MapIndex(0x15fe060, 0xc00043cf08, 0x195, 0x15896a0, 0xc00057f5a0, 0x98, 0x4ebd05, 0xc0006a7970, 0x179d096)
[2021-01-30T10:31:19.390Z] 	/go/src/reflect/value.go:1188 +0x16e fp=0xc000c5a6e8 sp=0xc000c5a670 pc=0x4d634e
[2021-01-30T10:31:19.390Z] encoding/json.mapEncoder.encode(0x1846648, 0xc000be9a80, 0x15fe060, 0xc00043cf08, 0x195, 0x15d0100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:801 +0x30d fp=0xc000c5a860 sp=0xc000c5a6e8 pc=0x57fecd
[2021-01-30T10:31:19.390Z] encoding/json.mapEncoder.encode-fm(0xc000be9a80, 0x15fe060, 0xc00043cf08, 0x195, 0xc000430100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:777 +0x65 fp=0xc000c5a8a0 sp=0xc000c5a860 pc=0x58c2c5
[2021-01-30T10:31:19.390Z] encoding/json.ptrEncoder.encode(0xc000424790, 0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0x1600100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:915 +0x125 fp=0xc000c5a960 sp=0xc000c5a8a0 pc=0x580ee5
[2021-01-30T10:31:19.390Z] encoding/json.ptrEncoder.encode-fm(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0x2310100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:900 +0x65 fp=0xc000c5a9a0 sp=0xc000c5a960 pc=0x58c445
[2021-01-30T10:31:19.390Z] encoding/json.(*encodeState).reflectValue(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0xc000c50100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:358 +0x82 fp=0xc000c5a9d8 sp=0xc000c5a9a0 pc=0x57d062
[2021-01-30T10:31:19.390Z] encoding/json.(*encodeState).marshal(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0xc000060100, 0x0, 0x0)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:330 +0xf4 fp=0xc000c5aa38 sp=0xc000c5a9d8 pc=0x57cc54
[2021-01-30T10:31:19.390Z] encoding/json.(*Encoder).Encode(0xc000c5aaf8, 0x160ff00, 0xc00043cf08, 0xc000068800, 0x7fb2fc0407d0)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/stream.go:206 +0x8b fp=0xc000c5aac8 sp=0xc000c5aa38 pc=0x589dab
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/types.(*NodeSelector).String(0xc00043cf08, 0xc00043cf08, 0xb0)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/types/types.go:37 +0xb0 fp=0xc000c5ab58 sp=0xc000c5aac8 pc=0xc12390
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects.func1(0xc000721d00)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:84 +0xd65 fp=0xc000c5afe0 sp=0xc000c5ab58 pc=0x13ff2a5
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.loadYAML(0xc0000419e0, 0x28, 0xc000c5b228, 0xc000c5b218, 0xc000c5b208, 0xc0000419e0, 0x28, 0x179cfee, 0x4, 0x179eb01)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:328 +0x60b fp=0xc000c5b160 sp=0xc000c5afe0 pc=0x13fe50b
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects(0x1, 0x14, 0x179cbc2, 0x3, 0x17a4e67, 0xe, 0xc0009db820, 0x11, 0xc0009db840, 0x1a, ...)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:160 +0x1d8 fp=0xc000c5b278 sp=0xc000c5b160 pc=0x13fc418
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/test/e2e/operator/validate.DriverDeployment(0x1999e40, 0xc000cf1600, 0x1, 0x14, 0x17a4e67, 0xe, 0xc0009db820, 0x11, 0xc0009db840, 0x1a, ...)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/test/e2e/operator/validate/validate.go:125 +0x205 fp=0xc000c5b950 sp=0xc000c5b278 pc=0x1400ec5
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.5(0xc000753e60, 0xc000f24000, 0xc000310c60, 0x2, 0x2, 0x1)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:359 +0x194 fp=0xc000c5be90 sp=0xc000c5b950 pc=0x14ca5f4
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.9.1.1(0xc00005cb01)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:585 +0x765 fp=0xc000c5bf68 sp=0xc000c5be90 pc=0x14cc085
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.9.1.3(0xc001542600)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:595 +0x2a fp=0xc000c5bf80 sp=0xc000c5bf68 pc=0x14cc1aa
[2021-01-30T10:31:19.390Z] testing.tRunner(0xc001542600, 0xc000da6080)
[2021-01-30T10:31:19.390Z] 	/go/src/testing/testing.go:1127 +0xef fp=0xc000c5bfd0 sp=0xc000c5bf80 pc=0x521a6f
[2021-01-30T10:31:19.390Z] runtime.goexit()
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000c5bfd8 sp=0xc000c5bfd0 pc=0x471081
[2021-01-30T10:31:19.390Z] created by testing.(*T).Run
[2021-01-30T10:31:19.390Z] 	/go/src/testing/testing.go:1178 +0x386
```

**Comment by pohly** [comment]
> One more concurrent map access random failure:

Please provide links in addition to snippets.

**Comment by pohly** [comment]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-866/4/pipeline

**Comment by pohly** [comment]
`go test -race ./pkg/pmem-csi-operator/controller/deployment/` points out one issue:
```
==================
WARNING: DATA RACE
Write at 0x00c00028cbd0 by goroutine 220:
  runtime.mapassign()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:571 +0x0
  reflect.mapassign()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:1319 +0x3e
  github.com/json-iterator/go.(*placeholderDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:324 +0x64
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*generalStructDecoder).decodeOneField()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:552 +0x1e4
  github.com/json-iterator/go.(*generalStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:508 +0x10f
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*twoFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:617 +0x58d
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:735 +0x169
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:741 +0x654
  github.com/json-iterator/go.(*Iterator).ReadVal()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:79 +0x1fb
  github.com/json-iterator/go.(*frozenConfig).Unmarshal()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:348 +0xfe
  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/json/json.go:263 +0x541
  k8s.io/apimachinery/pkg/runtime/serializer/recognizer.(*decoder).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/recognizer/recognizer.go:107 +0x617
  k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/versioning/versioning.go:136 +0xf4
  sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeClient).Patch()
      /nvme/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/client/fake/client.go:501 +0x976
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testClient).Patch()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:756 +0x13e
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*objectPatch).apply()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:192 +0x919
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).redeploy()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:329 +0x4b9
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).reconcile.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:233 +0x284
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).reconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:242 +0x461
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*ReconcileDeployment).Reconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:322 +0xa84
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testContext).testReconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:155 +0xcf
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testContext).testReconcilePhase()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:165 +0x64
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.8()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:533 +0x72d
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Previous read at 0x00c00028cbd0 by goroutine 226:
  reflect.maplen()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:1351 +0x0
  reflect.Value.MapKeys()
      /nvme/gopath/go-1.15.2/src/reflect/value.go:1212 +0x3a4
  encoding/json.mapEncoder.encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:785 +0x10f
  encoding/json.mapEncoder.encode-fm()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:777 +0x84
  encoding/json.ptrEncoder.encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:915 +0x1c4
  encoding/json.ptrEncoder.encode-fm()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:900 +0x84
  encoding/json.(*encodeState).reflectValue()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:358 +0x93
  encoding/json.(*encodeState).marshal()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:330 +0xd2
  encoding/json.(*Encoder).Encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/stream.go:206 +0xdd
  github.com/intel/pmem-csi/pkg/types.(*NodeSelector).String()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/types/types.go:37 +0xf0
  github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:84 +0x12c4
  github.com/intel/pmem-csi/pkg/deployments.loadYAML()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:328 +0x835
  github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:160 +0x1ef
  github.com/intel/pmem-csi/test/e2e/operator/validate.DriverDeployment()
      /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/operator/validate/validate.go:125 +0x324
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.5()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:359 +0x23b
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.8()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:534 +0x815
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Goroutine 220 (running) created at:
  testing.(*T).Run()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1178 +0x796
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:500 +0x23a5
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func2()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:720 +0x58
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Goroutine 226 (running) created at:
  testing.(*T).Run()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1178 +0x796
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:500 +0x23a5
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func2()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:720 +0x58
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202
==================
```

Line 534 is: https://github.com/intel/pmem-csi/blob/90dfa119a909640c06a7700dd3f973bef88ce38a/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go#L534

`updatedDep` is written in https://github.com/intel/pmem-csi/blob/90dfa119a909640c06a7700dd3f973bef88ce38a/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go#L515

There is indeed no synchronization.

**Comment by pohly** [comment]
Fixed the one above. Then there's one which is closer to what we've seen in the CI. By bumping up `history_size` we get a full stack trace for both goroutines:

```
$ GORACE="history_size=7" go test -race ./pkg/pmem-csi-operator/controller/deployment/
...
==================
WARNING: DATA RACE
Write at 0x00c00028abd0 by goroutine 219:
  runtime.mapassign()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:571 +0x0
  reflect.mapassign()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:1319 +0x3e
  github.com/json-iterator/go.(*placeholderDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:324 +0x64
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*generalStructDecoder).decodeOneField()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:552 +0x1e4
  github.com/json-iterator/go.(*generalStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:508 +0x10f
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*twoFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:617 +0x58d
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:737 +0x58d
  github.com/json-iterator/go.(*structFieldDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0xcd
  github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:741 +0x654
  github.com/json-iterator/go.(*Iterator).ReadVal()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:79 +0x1fb
  github.com/json-iterator/go.(*frozenConfig).Unmarshal()
      /nvme/gopath/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:348 +0xfe
  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/json/json.go:263 +0x541
  k8s.io/apimachinery/pkg/runtime/serializer/recognizer.(*decoder).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/recognizer/recognizer.go:107 +0x617
  k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode()
      /nvme/gopath/pkg/mod/k8s.io/apimachinery@v0.19.1-rc.0/pkg/runtime/serializer/versioning/versioning.go:136 +0xf4
  sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeClient).Patch()
      /nvme/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/client/fake/client.go:501 +0x976
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testClient).Patch()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:774 +0x13e
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*objectPatch).apply()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:192 +0x919
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).redeploy()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:329 +0x4b9
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).reconcile.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:233 +0x284
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*pmemCSIDeployment).reconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/controller_driver.go:242 +0x461
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment.(*ReconcileDeployment).Reconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:322 +0xa84
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testContext).testReconcile()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:155 +0xcf
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.(*testContext).testReconcilePhase()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:165 +0x64
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.8()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:551 +0x764
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Previous read at 0x00c00028abd0 by goroutine 217:
  reflect.maplen()
      /nvme/gopath/go-1.15.2/src/runtime/map.go:1351 +0x0
  reflect.Value.MapKeys()
      /nvme/gopath/go-1.15.2/src/reflect/value.go:1212 +0x3a4
  encoding/json.mapEncoder.encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:785 +0x10f
  encoding/json.mapEncoder.encode-fm()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:777 +0x84
  encoding/json.ptrEncoder.encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:915 +0x1c4
  encoding/json.ptrEncoder.encode-fm()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:900 +0x84
  encoding/json.(*encodeState).reflectValue()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:358 +0x93
  encoding/json.(*encodeState).marshal()
      /nvme/gopath/go-1.15.2/src/encoding/json/encode.go:330 +0xd2
  encoding/json.(*Encoder).Encode()
      /nvme/gopath/go-1.15.2/src/encoding/json/stream.go:206 +0xdd
  github.com/intel/pmem-csi/pkg/types.(*NodeSelector).String()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/types/types.go:37 +0xf0
  github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:84 +0x12c4
  github.com/intel/pmem-csi/pkg/deployments.loadYAML()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:328 +0x835
  github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/deployments/load.go:160 +0x1ef
  github.com/intel/pmem-csi/test/e2e/operator/validate.DriverDeployment()
      /nvme/gopath/src/github.com/intel/pmem-csi/test/e2e/operator/validate/validate.go:125 +0x324
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.5()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:359 +0x23b
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.8()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:552 +0x851
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Goroutine 219 (running) created at:
  testing.(*T).Run()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1178 +0x796
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:500 +0x23a5
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func2()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:738 +0x58
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202

Goroutine 217 (running) created at:
  testing.(*T).Run()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1178 +0x796
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:500 +0x23a5
  github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func2()
      /nvme/gopath/src/github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:738 +0x58
  testing.tRunner()
      /nvme/gopath/go-1.15.2/src/testing/testing.go:1127 +0x202
==================
```

**Comment by pohly** [comment]
That one is harder to explain. Both goroutines are created at `deployment_controller_test.go:500`, which is `t.Run("modified deployment under reconcile", func(t *testing.T) {` - this looks like test runs for different Kubernetes versions (outer look). They shouldn't share *any* data.

**Comment by pohly** [comment]
I've added printing of the `NodeSelector` pointer to loading and patching and I get:
```
I0201 11:10:44.086513  101933 controller_driver.go:174] patching daemonset with nodeselector 0xc0001c8ba0
I0201 11:10:44.097293  101933 load.go:83] loading with nodeselector 0xc0001c8ba0
I0201 11:10:44.098232  101933 load.go:83] loading with nodeselector 0xc0001c8ba0
I0201 11:10:44.100432  101933 load.go:83] loading with nodeselector 0xc0001c8ba0
I0201 11:10:44.102488  101933 load.go:83] loading with nodeselector 0xc0001c8ba0
I0201 11:10:44.105622  101933 load.go:83] loading with nodeselector 0xc0001c8ba0
==================
WARNING: DATA RACE
Write at 0x00c0001c8ba0 by goroutine 215:
  runtime.mapassign()
      /nvme/gopath/go-1.15.7/src/runtime/map.go:571 +0x0
  reflect.mapassign()
...
```

According to this, the `DaemonSet` being patched and the `PmemCSIDeployment` used by load share the same `NodeSelector` map.

It is true that we just copy the map pointer when generating the `DaemonSet`. But then we hand it over to the fake client, which should store a deep copy. I've traced it down through the fake client to https://github.com/kubernetes/client-go/blob/a1a652a556b5092f0f61b9c63a7ebfb814a7fa9d/testing/fixture.go#L367-L376 which does indeed store a deep copy.

Ah, but `redeploy` does indeed patch an object that was generated, i.e. not stored yet. Furthermore, according to https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#Writer the `Patch` function is writing into the object that it is given. Here we have our broken write into a map that should be read-only!

**Comment by pohly** [comment]
Cloning before `Patch()` fixes it.

**Comment by pohly** [comment]
This is the known issue from #852

**Review by pohly — APPROVED** [review]

**Pull request merged**
