### PR TITLE
operator: Add missing deployment status conditions.

### LINKED ISSUE #819: Missing events and  condition after deployment
Just run latest operator and pmem-csi: `intel/pmem-csi-driver:canary`
In `kubectl describe deployment.pmem-csi.intel.com/pmem-csi.intel.com` -  i got missing events and missing condition
`  Type:              DriverDeployed`  as shown in https://github.com/intel/pmem-csi/blob/devel/docs/install.md.

All pods are running ok:
```
NAME                                 READY   STATUS    RESTARTS   AGE
pmem-csi-intel-com-controller-0      2/2     Running   0          11h
pmem-csi-intel-com-node-8cksq        2/2     Running   0          11h
pmem-csi-intel-com-node-dv8px        2/2     Running   0          11h
pmem-csi-intel-com-node-ldbps        2/2     Running   0          11h
pmem-csi-intel-com-node-lpljv        2/2     Running   0          11h
pmem-csi-intel-com-node-qnwqg        2/2     Running   0          11h
pmem-csi-intel-com-node-rsbn9        2/2     Running   0          11h
pmem-csi-intel-com-node-zkhf4        2/2     Running   0          11h
pmem-csi-operator-57c7c5cf8d-h687f   1/1     Running   0          11h
```

No errors in the logs, all volume groups are created.

```[solben@utility1 helpers]$ kubectl describe deployment.pmem-csi.intel.com/pmem-csi.intel.com
Name:         pmem-csi.intel.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  pmem-csi.intel.com/v1alpha1
Kind:         Deployment
Metadata:
  Creation Timestamp:  2020-11-17T21:46:46Z
  Generation:          1
  Managed Fields:
    API Version:  pmem-csi.intel.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:deviceMode:
    Manager:      kubectl
    Operation:    Update
    Time:         2020-11-17T21:46:46Z
    API Version:  pmem-csi.intel.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:driverComponents:
        f:lastUpdated:
        f:phase:
        f:reason:
    Manager:         pmem-csi-operator
    Operation:       Update
    Time:            2020-11-17T21:46:56Z
  Resource Version:  151455
  Self Link:         /apis/pmem-csi.intel.com/v1alpha1/deployments/pmem-csi.intel.com
  UID:               ff2a549c-2db3-4397-b3a5-1280f1d448cf
Spec:
  Device Mode:  lvm
Status:
  Conditions:
    Last Update Time:  2020-11-17T21:46:50Z
    Reason:            Driver certificates are available.
    Status:            True
    Type:              CertsReady
  Driver Components:
    Component:     Controller
    Last Updated:  2020-11-17T21:46:56Z
    Reason:        1 instance(s) of controller driver is running successfully
    Status:        Ready
    Component:     Node
    Last Updated:  2020-11-17T21:46:52Z
    Reason:        All 7 node driver pod(s) running successfully
    Status:        Ready
  Last Updated:    2020-11-17T21:46:56Z
  Phase:           Running
  Reason:          All driver components are deployed successfully
Events:            <none>
```

### PR DESCRIPTION
**Pull request by avalluri**
`DriverDeployed` and `CertsVerified` in case of verification failure
status conditions were missing.

Also added conditions validation in unit tests.

FIXES #819

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
Can you also add something to an E2E test? It doesn't need to cover as many cases as the unit tests and it is less likely to break on a real cluster compared to emitting events, but we still need to verify at least the basic path once.

**Comment by avalluri** [comment]
> Can you also add something to an E2E test? It doesn't need to cover as many cases as the unit tests and it is less likely to break on a real cluster compared to emitting events, but we still need to verify at least the basic path once.

Added the condition validation appropriate tests to cover different cases.

**Comment by avalluri** [comment]
@pohly Do you have any guess what might be causing `Testing / 1.17 / works – fedora-1_17.direct-testing-metrics`  test failure, which is not supposed to be the result of this change.

**Comment by pohly** [comment]
> Do you have any guess what might be causing Testing / 1.17 / works – fedora-1_17.direct-testing-metrics test failure, which is not supposed to be the result of this change.

There's apparently a small race condition: one metric about CSI calls is only present in the metrics data if at least one CSI call has been recorded. During startup that might not have happened yet. I've add https://github.com/intel/pmem-csi/issues/822

**Review by pohly — APPROVED** [review]

**Pull request merged**
