### PR TITLE
deploy: give driver-registrar more time for requests

### PR DESCRIPTION
**Pull request by pohly**
This addresses a (rare?) test flake.

Fixes: https://github.com/intel/pmem-csi/issues/936

### CODE REVIEW

**Comment by pohly** [comment]
Only one test flake. @avalluri okay to merge?

**Comment by avalluri** [comment]
> Only one test flake. @avalluri okay to merge?

I think ok to merge, I will investigate that failure separtely.

**Review by avalluri — APPROVED** [review]

**Comment by avalluri** [comment]
> I think ok to merge, I will investigate that failure separately.

I doubt if this object update caused by the operator was 'unexpected'. As per the below logs from https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/job/PR-941/1/artifact/joblog-jenkins-pmem-csi-PR-941-1-test-1.20.log:

```
[It] runs
  /mnt/workspace/pmem-csi_PR-941/test/e2e/operator/driver.go:37
I0423 17:25:11.557731   12379 client.go:57] Kubernetes version read from server: 1.20
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.801552       1 deployment_controller.go:126] "UPDATED" object="default/second-pmem-csi-intel-com-node-setup <*v1.DaemonSet>"
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.802625       1 deployment_controller.go:466] "newDeployment: load controller TLS secret" secret="default/second-pmem-csi-intel-com-controller-secret" CAlength=1086
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.802743       1 controller_driver.go:628] "deployment/event: start" object="default/second-pmem-csi-intel-com-node-setup <*v1.DaemonSet>" type="*v1.DaemonSet"
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.803442       1 controller_driver.go:642] "deployment/event: redeploying" name="node setup driver" object="default/second-pmem-csi-intel-com-node-setup <*v1.DaemonSet>"
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.805775       1 controller_driver.go:194] "redeploy/getSubObject: get" object="default/second-pmem-csi-intel-com-node-setup <*v1.DaemonSet>"
pmem-csi-operator-59c78d899c-swgfk/pmem-csi-operator@pmem..ker1: I0423 17:25:20.847540       1 deployment_controller.go:67] "UPDATED" object="second.pmem-csi.intel.com <*v1beta1.PmemCSIDeployment>" generation=1
```

I guess, the 'update' on node-setup daemonset was initiated outside of the operator coming from an earlier test, i.e, "raw conversion works".  

I believe we should fix the 'driver runs' test such that, it runs a fresh driver instance(instead of relying on a pre-deployed driver) and ensures that the deployed objects are consistent.

**Comment by pohly** [comment]
Let's discuss in https://github.com/intel/pmem-csi/issues/887

**Pull request merged**
