### PR TITLE
Olm catalog: Various fixes

### PR DESCRIPTION
**Pull request by avalluri**
Various fixes to generated CVS:
 - add missing mandatory fields.
 - set date of CVS to the current date.
 - make 'AllNamespaces' install mode to false.
 - fix an issue in version patching.

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
Looks good, but before we merge, let's investigate whether we can extend our testing to catch these issues.

**Comment by pohly** [comment]
From https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-792/3/pipeline

```
[2020-10-27T23:04:54.503Z] curl -L https://github.com/operator-framework/operator-courier/archive/v2.1.10.tar.gz | tar -zxf -C _work/
[2020-10-27T23:04:54.503Z] tar (child): -C: Cannot open: No such file or directory
[2020-10-27T23:04:54.503Z] tar (child): Error is not recoverable: exiting now
```

**Comment by avalluri** [comment]
> From https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-792/3/pipeline
> 
> ```
> [2020-10-27T23:04:54.503Z] curl -L https://github.com/operator-framework/operator-courier/archive/v2.1.10.tar.gz | tar -zxf -C _work/
> [2020-10-27T23:04:54.503Z] tar (child): -C: Cannot open: No such file or directory
> [2020-10-27T23:04:54.503Z] tar (child): Error is not recoverable: exiting now
> ```

Wrong argument `-f` for tar. Fixed it now. And fixed a typo in one of the commit messages.

**Review by pohly — APPROVED** [review]
Looks good.

Because E2E testing includes using the generated files, we do have test coverage.

**Pull request merged**
