### PR TITLE
CreateDevice: avoid space-exhaustion loop on partial volume creation failure

### LINKED ISSUE #168: space on device exhausted if /dev from host is not imported in container
Recently discovered deployment error in #167 exposes nasty error-loop scenario where all space on device gets quickly consumed, leading to denial-of-service state.
Although the bad state is a side-effect of another error, we should try to make pmem-csi plugin more robust against such scenario.
What happens is this in ControllerPublishVolume:
if VolumeID not published:
  - status = (create namespace AND zero begin of it)
  - return if error
  - mark VolumeID published

Failure happens in "zero begin of it" part, making the 1st half succeed, but 2nd half failed,
Zeroing fails because /dev is not imported into pod container and container does not see the device.
After "return if error" part, Kubernetes repeats the call with same VolumeID instantly
and we reserve next piece of same size. This repeats until device runs out of space.
The (many) allocated namespaces have same VolumeID recorded in their Name field, making one of those  useful in some next stages, but all the others will remain orphaned.
We should improve by trying one of: 
- next allocation should re-use allocated namespace for that VolumeID, this requires that we start recording created namespaces immediately after creation succeeds, not just at "mark" part.
(needs changes as both "create" and "zero" ops are isolated in the dev-manager layer now).
- at "return if error" part we restore previous state, i.e. destroy orphaned namespace

### PR DESCRIPTION
**Pull request by okartau**
There was failure scenario in devicemode:direct where namespace
creation succeeded but zeroing of device did not, i.e. partial
success, but returned FAIL, which caused k8s to repeat,
and as created namespace remained there, all device space
was quickly consumed. We address this by trying to clean up
on partial failure.

Fixes #168

### CODE REVIEW

**Comment by okartau** [comment]
interesting... current PR code (ndctl part) fails to destroy namespace (if we add checking for error):
`Destroy returned: failed to disable namespace: No such file or directory`
This is pretty bad, as it blocks us from removing, even if the force arg is set to TRUE.
More investigation needed.
Deletion must be possible as I can delete such namespaces from command line using ndctl.
But the difference from CLI is, this code runs inside container, without /dev/ mounted.

**Comment by okartau** [comment]
Another approach. As it seems we can not clean up by deleting, lets avoid creating next namespace for request with same name (i.e. VolumeID). As such namespace exists, we return OK. This leads to failure in next step: StageVolume as file system creation will fail (as there is no device). But as whole plugin is in non-functional state at that point, it does not matter much in which stage we fail.
At least we avoid repeated creation of same-name object which instantly eats up all the space in host.
Overall, refusal to create same-name object makes sense as this name (VolumeID) is used to look up namespace later, so having more than one with same name makes no sense.
Although the error state so far has been seen in devicemode:direct, I add same check on LVM2 side as well, for uniformity.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Another approach. As it seems we can not clean up by deleting, lets
> avoid creating next namespace for request with same name
> (i.e. VolumeID). As such namespace exists, we return OK. This leads to
> failure in next step: StageVolume as file system creation will fail
> (as there is no device). But as whole plugin is in non-functional
> state at that point, it does not matter much in which stage we fail.

Calls are supposed to be idempotent. That means that calls have to
succeed eventually when called multiple times.

When you say "plugin is in non-functional state", what exactly does that
mean?  How does that happen and do users recover from that state?

**Comment by okartau** [comment]
> When you say "plugin is in non-functional state", what exactly does that mean? How does that happen and do users recover from that state?

Specifically here I describe related state I saw when debugging state of #167. It is possible to get pmem-csi plugin running so that /dev/ is not passed into container. Such problematic state is not detected/flagged (not at least by current code, worth trying perhaps, not even sure how can it be done...).
The operating result in such state will be mixed and lead to space exhaustion, because namespace creation will work, but /dev/pmemX.Y device will not appear inside container, i.e. plugin can not provision volume and file system on top of that namespace.
That's what I mean with "non-functional":plugin will not provision anything anyway.

It's true this is result of mis-configuration, invalid manifest, changes in containering layer, etc. such issues, but we can not rule out bad things can happen, and I think we should minimize bad impact. The impact would be device filled with garbage entries which need manual cleanup.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

>> When you say "plugin is in non-functional state", what exactly does that mean? How does that happen and do users recover from that state?
>
> Specifically here I describe related state I saw when debugging state
> of #167. It is possible to get pmem-csi plugin running so that /dev/
> is not passed into container. Such problematic state is not
> detected/flagged (not at least by current code, worth trying perhaps,
> not even sure how can it be done...).

In that case it makes sense to fail permanently and ideally without
causing more breakage, so this PR is an improvement.

**Comment by okartau** [comment]
one more thing to think here, is it good idea to return OK if same-name namespace already detected,
or should we return error instead. I will try both ways.

**Comment by okartau** [comment]
I tried with return of error "namespace with same name exists", end result is same, plugin is called number of times with same request (18 times), then calling stops(pauses?).
I think I will change code in PR to return error instead of OK, to be more clear.

**Comment by okartau** [comment]
code changed now to return error, force pushed.
OK to merge?

**Comment by avalluri** [comment]
@okartau sorry for late comments, in my opinion CreateDevice calling with existing volume name/id shouldn't return error, instead it should return the same device. If i understood correct, the failure occurrence was in "ClearDevice", in that case we should delete the newly created device and return err. Instead of returning error

**Comment by okartau** [comment]
I start to feel more and more that current PR tries to put rubberband fix around already badly broken state-
Instead, we should try to implement detection enabling to avoid entering such state, like I expressed in recent comment under #112.
If we can detect /dev in container which is isolated i.e. not mounted from host, and we are in devicemode:direct, then we should not even start running, thus avoiding creation bad namespace entries. There is no point running if any provision attempt is known to become failure.

**Comment by okartau** [comment]
Change in this PR seems the best we can do right now, so I propose to merge this, allowing to close currently open issues about this topic

**Comment by okartau** [comment]
ok to merge? any comments?

**Pull request merged**
