### PR TITLE
Jenkinsfile: add k8s 1.15 testing, using Clear=31070

### PR DESCRIPTION
**Pull request by okartau**

### CODE REVIEW

**Comment by okartau** [comment]
Fails at `scp $SSH_ARGS ${CLOUD_USER}@${master_ip}:.kube/config $KUBECONFIG`
but not likely this is 1.15 related, or is it.

**Comment by pohly** [comment]
> Fails at scp $SSH_ARGS ${CLOUD_USER}@${master_ip}:.kube/config $KUBECONFIG

In my experience that is the result of some cluster setup error earlier - `.kube/config` then simply doesn't exist.

**Comment by pohly** [comment]
The only vm which actually finished "swupd update" seems to be "worker1". Not sure what happened to the others. We need better error handling in the code which handles that :frowning:

**Comment by okartau** [comment]
I added -xe args to shell, to see more what is going on, and -e I think is overall useful in test systems, to clarify where the error happens (unless there is good reason not to use -e)

**Comment by okartau** [comment]
worth noting also that I ran twice locally 'make start' with Clear=31070 without problems, but on CI it was 2/2 fail (although not deterministic failure as 1st CI run succeeded LVM part and failed only in direct part)

**Comment by okartau** [comment]
hm, I just realized errecit gets set on different line

**Comment by pohly** [comment]
> I added -xe args to shell, to see more what is going on, and -e I think is overall useful in test systems, to clarify where the error happens (unless there is good reason not to use -e)

`-e` is only a band-aid and shouldn't be relied upon for error handling (http://mywiki.wooledge.org/BashFAQ/105, https://fvue.nl/wiki/Bash:_Error_handling#Caveat_2:_.60Exit_on_error.27_not_exitting_subshell_on_error).

There's simply too much with it that doesn't work as expected.

**Comment by okartau** [comment]
I wonder can this play a role here:
```
    if [ "$TEST_CLEAR_LINUX_VERSION" -ge 29920 ]; then
        CLOUD_IMAGE="clear-$TEST_CLEAR_LINUX_VERSION-cloudguest.img.xz"
    else
        CLOUD_IMAGE="clear-$TEST_CLEAR_LINUX_VERSION-cloud.img.xz"
    fi
```
The new version is first one above the limit compared here, so we pick different image.

**Comment by okartau** [comment]
CI log says "kubeadm not found" on VMs. Is clear-31070-cloudguest.img.xz really without that?
More confusion: how come local run of 'make start' works, using same 31070-cloudguest image?

**Comment by pohly** [comment]
Where you see "kubeadm not found"? It's not in https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-422/runs/3/nodes/68/steps/77/log/?start=0

**Comment by pohly** [comment]
`cloudguest` is the correct image for recent Clear Linux.

**Comment by pohly** [comment]
What I've done in the past to debug such issues that only occur in the CI was to log into the worker machines while a job was running. We need to ask Chuy whether (and how) that is still possible.

**Comment by avalluri** [comment]
> Where you see "kubeadm not found"? It's not in https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/PR-422/runs/3/nodes/68/steps/77/log/?start=0

Maybe @okartau  referring to this:
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-422/3/pipeline#step-73-log-3275

**Comment by okartau** [comment]
yes,
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-422/3/pipeline
line 3275 and forward

**Comment by okartau** [comment]
seems repeated runs produce different results which is not desirable feature of CI

**Comment by avalluri** [comment]
What does really this means:
```
++ tee -a /mnt/workspace/pmem-csi_PR-422/_work/clear/pmem-csi-clear-master.log
++ echo '10:53:19 pmem-csi-clear-master: I0930 10:53:19.167809   10538 version.go:248] remote version is much newer: v1.16.0; falling back to: stable-1.15'
10:53:19 pmem-csi-clear-master: I0930 10:53:19.167809   10538 version.go:248] remote version is much newer: v1.16.0; falling back to: stable-1.15
```

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-422/3/pipeline
> line 3275 and forward

Ah, the first attempt. The second attempt then fails differently. This
is another problem with the scripts, the cleanup step is often
incomplete.

Why kubeadm is not found is an open question. It should be in
cloud-native-basic.

**Comment by okartau** [comment]
very fuzzy, multiple different errors from CI. At same time, `make start` keeps working OK for me (tried 3 times). Are all errors CI-specific then?

**Comment by pohly** [comment]
I found one reason why error handling isn't working: `wait` without parameters waits for all commands, then returns with 0 exit code even when some command has failed.

**Comment by okartau** [comment]
closing as  this was covered by recently merged #423

**Pull request closed without merging**
