### PR TITLE
vendor update

### PR DESCRIPTION
**Pull request by pohly**
Reverts to upstream Kubernetes and ensures that we are up-to-date.

Used to contain preparations for Go 1.13, but those commits were already merged elsewhere.

### CODE REVIEW

**Comment by okartau** [comment]
"test: Go 1.3 + TLS 1.3 error handling" commit should mention Go 1.13 instead of 1.3 ? (also same in commit-text)

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> "test: Go 1.3 + TLS 1.3 error handling" commit should mention Go 1.13
> instead of 1.3 ?

Fixed. I believe TLS 1.3 rubbed of on the Go version ;-}

**Comment by okartau** [comment]
now CI test seem to panic same way as I saw in #414

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> now CI test seem to panic same way as I saw in #414

Yes, that's expected. It worked when I locally applied the patch that I
submitted upstream.

We could take your PR as an intermediate solution.

**Comment by pohly** [comment]
My initial version accidentally didn't run any E2E tests because `TestMain` lacked the necessary `Run` invocation at the end. Now that's fixed and tests fail, as they should.

**Comment by avalluri** [comment]
@pohly I think we can close this PR as the needed changes from this, merged via other PRs.

**Comment by pohly** [comment]
I'm pretty sure there are parts of this PR which haven't been merged yet. I'll rebase when I'm back.

**Comment by avalluri** [comment]
This change also updating `csi-test` package to v2.3.0, which is handled in # 447, If the intention of this change is to revert Kubernetes fork, I would suggest running `dep ensure` instead of `update`.

**Comment by pohly** [comment]
The intention is to update to the latest releases of all our dependencies. @okartau just happened to update csi-test in parallel. IMHO both PRs are ready for merging.

**Comment by okartau** [comment]
don't let #447 to disturb, we can forget it if some other PR brings same change. I just created it to have it visible (and CI tested) separately. Or, the other way is also possible, can merge #447 and reduce it from another change. End result will be same.

**Comment by pohly** [comment]
Let's merge #447, then this one.

**Pull request merged**
