### PR TITLE
operator: Stop support for 1.17 in favor of avoid using deprecated `storage.k8s.io/v1beta1` API

### LINKED ISSUE #854: Remove Kubernetes 1.17 support
Once we have added support for Kubernetes 1.20 (issue #853), we'll be testing against four releases in our CI. We might want to remove support and testing against 1.17 because:
- faster CI testing
- it allows removing usage of deprecated beta APIs (issue #844)

### PR DESCRIPTION
**Pull request by avalluri**
CSIDriver API has moved to v1 and v1beta1 is deprecated in v1.19 and is
not recommended to use the later versions.

```
W1229 16:52:38.338157       1 warnings.go:67] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
```
As a side effect had to upgrade to the latest kustomize as the v3.8.2 is
not capable of recognizing v1 CSIDriver as cluster-scoped object and
skipping from namespace patching.

FIXES #854

### CODE REVIEW

**Comment by pohly** [comment]
I thought we needed 1.19 as minimum Kubernetes version for the v1 API (https://github.com/intel/pmem-csi/issues/726)?

**Comment by avalluri** [comment]
> I thought we needed 1.19 as minimum Kubernetes version for the v1 API (#726)?

As per [CSI documentation](https://kubernetes-csi.github.io/docs/csi-driver-object.html) CSIDriver has moved to GA(v1) in Kubernetes 1.18. I made the changes to both driver manifests and the operator to us `v1beta1` for <= 1.18 and `v1` for 1.19+.

**Review by pohly — CHANGES_REQUESTED** [review]
Sorry, but this is way to complex just to get rid of some completely harmless warning.

Let's wait until we no longer need to support 1.17 (which is basically now) and then use v1 everywhere.

We can drop support for 1.17 now and only support 1.18, 1.19, 1.20.

**Comment by pohly** [comment]
>  @avalluri avalluri force-pushed the avalluri:csidriver branch from f044b03 to d2f8f8d 5 hours ago 

I see no reason to continue working on this PR.

**Comment by pohly** [comment]
@avalluri do you agree that we can close this?

**Comment by avalluri** [comment]
> @avalluri do you agree that we can close this?

Okay, but the repeated warning messages are so annoying and makes the logs hard for debugging. Would be good to come conclusion about 1.17 support so that we can revisit this PR.

**Review by pohly — COMMENTED** [review]
Commit 7c7549d30a0861b5fe69752f743fcb4deb23173e says "update kustomize version to 4.0.5" but I don't see a version bump in it, only the `--load-restrictor LoadRestrictionsNone` change.

**Comment by avalluri** [comment]
> Commit [7c7549d](https://github.com/intel/pmem-csi/commit/7c7549d30a0861b5fe69752f743fcb4deb23173e) says "update kustomize version to 4.0.5" but I don't see a version bump in it, only the `--load-restrictor LoadRestrictionsNone` change.

Yes, I just realized. It got lost in rebasing. Fixed it now.

**Review by pohly — APPROVED** [review]

**Pull request merged**
