### PR TITLE
docsite artifact in Jenkins

### PR DESCRIPTION
**Pull request by pohly**
A superset of https://github.com/intel/pmem-csi/pull/562

### CODE REVIEW

**Comment by pohly** [comment]
Change was merged into the original PR.

**Comment by pohly** [comment]
Let me do another trial run with a fix for "make vhtml". I also want to see whether Jenkins now runs the "docsite" stage.

@intelkevinputnam

**Comment by pohly** [comment]
I pushed the latest content from https://github.com/intel/pmem-csi/pull/562 with some minor fixes (warning about `_static`, commit message).

**Comment by pohly** [comment]
@intelkevinputnam: are the additional changes on top of your's okay?

Then let's merge this PR instead of #562 

I checked that docsite creation still works in Jenkins. There's just one caveat: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-571/Doc_20Site/ = https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-571/Doc_20Site/index.html does not redirect to https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/view/pmem-csi/job/pmem-csi/view/change-requests/job/PR-571/Doc_20Site/README.html. That threw me off initially.

Let's merge and see how that works when publishing to Github.

**Comment by intelkevinputnam** [comment]
@pohly Sounds good. One thing that you need to do on your side before this will work. Need to create an access token for a user that can write to the repo and save it as a secret in the repo settings: secrets.ACCESS_TOKEN.

**Comment by intelkevinputnam** [comment]
Also, the reason the redirect isn't happening is because the GitHub workflow handles that part in the deployment phase (see publish.yml).

**Comment by intelkevinputnam** [comment]
@pohly Thanks for your patience. :-) I'm going to guess that Actions are disabled for this repo at the moment, as I can't see the settings and it hasn't tried to build.

**Comment by pohly** [comment]
> I'm going to guess that Actions are disabled for this repo at the moment, as I can't see the settings and it hasn't tried to build.

I know, and I can't change those either. I've filed a ticket with our support team to get this changed.

**Pull request merged**
