### PR TITLE
docs: asciinema demo with thumnail preview

### PR DESCRIPTION
**Pull request by pohly**
This will show a static image that can be clicked on to play the
animated version. We could embed the player
script (https://asciinema.org/docs/embedding) but this may be
overkill.

Fixes: https://github.com/intel/pmem-csi/issues/664

### CODE REVIEW

**Comment by pohly** [comment]
@avalluri Is it obvious enough that the demo can be started by clicking?

See https://github.com/intel/pmem-csi/blob/994685254173cd85fbcb1413705890ec857a37b8/README.md#demo.

**Comment by avalluri** [comment]
> @avalluri Is it obvious enough that the demo can be started by clicking?
> 
> See https://github.com/intel/pmem-csi/blob/994685254173cd85fbcb1413705890ec857a37b8/README.md#demo.

Yes, I had a look at that. As you mentioned, embedding the video script overkills, then I feel It's ok to start the video by cling the screenshot.

**Comment by avalluri** [comment]
> First, add asciinema-player.js, asciinema-player.css and the .cast file with your recording to your site's assets.

So we need to have those three files to have an embedded video?, I think it's ok to have them in our source. What do you think.

**Comment by pohly** [comment]
> So we need to have those three files to have an embedded video?

No, the JS gets loaded from asciinema.org. I don't know how to get the necessary HTML tags into the rendered output, and it wouldn't work on GitHub.

I added some clarifying text instead.

**Pull request merged**
